site_name: glTF Tutorial
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - 'Introduction': gltfTutorial_001_Introduction.md
  - 'Basic glTF Structure': gltfTutorial_002_BasicGltfStructure.md
  - 'Example: A Minimal glTF File': gltfTutorial_003_MinimalGltfFile.md
  - 'Scenes and Nodes': gltfTutorial_004_ScenesNodes.md
  - 'Buffers, BufferViews, and Accessors': gltfTutorial_005_BuffersBufferViewsAccessors.md
  - 'Example: A Simple Animation': gltfTutorial_006_SimpleAnimation.md
  - 'Animations': gltfTutorial_007_Animations.md
  - 'Example: Simple Meshes': gltfTutorial_008_SimpleMeshes.md
  - 'Meshes': gltfTutorial_009_Meshes.md
  - 'Materials': gltfTutorial_010_Materials.md
  - 'Example: A Simple Material': gltfTutorial_011_SimpleMaterial.md
  - 'Textures, Images, and Samplers': gltfTutorial_012_TexturesImagesSamplers.md
  - 'Example: A Simple Texture': gltfTutorial_013_SimpleTexture.md
  - 'Example: An Advanced Material': gltfTutorial_014_AdvancedMaterial.md
  - 'Example: Simple Cameras': gltfTutorial_015_SimpleCameras.md
  - 'Cameras': gltfTutorial_016_Cameras.md
  - 'Example: A Simple Morph Target': gltfTutorial_017_SimpleMorphTarget.md
  - 'Morph Targets': gltfTutorial_018_MorphTargets.md
  - 'Example: Simple Skin': gltfTutorial_019_SimpleSkin.md
  - 'Skins': gltfTutorial_020_Skins.md
